apiVersion: v1
kind: Pod
metadata:
  name: nginx-app-task1
spec:
  containers:
    - name: nginx-task1
      image: nginx:1.26
      resources:
        requests:
          memory: "100Mi"
          cpu: 100m
        limits:
          memory: "100Mi"
          cpu: 100m
  initContainers:
    - name: init-echo
      image: busybox:1.28
      command: ["sh", "-c", "echo Initialization complete"]
      resources:
        requests:
          memory: "100Mi"
          cpu: 100m
        limits:
          memory: "100Mi"
          cpu: 100m