apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-app-task2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.26
          resources:
            requests:
              memory: "100Mi"
              cpu: 100m
            limits:
              memory: "100Mi"
              cpu: 100m