apiVersion: v1
kind: Pod
metadata:
  name: nginx-app-task4
spec:
  containers:
    - name: nginx
      image: nginx:1.26
      resources:
        requests:
          memory: "100Mi"
          cpu: 100m
        limits:
          memory: "100Mi"
          cpu: 100m
      env:
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: test-config-map
              key: APP_MODE

        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: test-config-map
              key: APP_PORT

      volumeMounts:
        - name: conf
          mountPath: "/etc/conf"
  volumes:
    - name: conf
      configMap: 
        name: test-config-map
        items: 
          - key: some_file
            path: test.conf